# DuckDB config reference:
config:
  send_anonymous_usage_stats: False
  use_colors: True

dbt_strava:
  target: dev
  outputs:
    dev:
      type: duckdb
      schema: strava_dev
      threads: 1
      path: "../reports/sources/strava_source/strava_datastack.duckdb"

    prod:
      type: duckdb
      schema: strava_prod
      threads: 1
      path: "../strava_datastack.duckdb"